---
- name: Add server to group Page on Patch Failure in itop.
  plops.general.ansible2itop:
    action: 'create'
    itop_url: 'https://itop.company.com/itop/web/webservices/rest.php?version=1.3'
    username: "{{itop_username}}"
    password: "{{itop_password}}"
    itop_class: 'lnkGroupToCI'
    validate_certs: no
    itop_fields:
      group_id: "SELECT Group WHERE name LIKE 'Page on Patch Failure'"
      ci_id: "SELECT VirtualMachine WHERE status!='decommissioned' AND name LIKE '{{ swvm['name'] }}'"
  ignore_errors: true
