---
- name: Sleep for 2 minutes
  pause:
    minutes: 2

- name: Wait for connection 
  wait_for:
    port: 22
    host: "{{ swvm['name'] }}"
    search_regex: SSH
    delay: 30
    timeout: 300

# You will need to run this so Ansible can understand the underlying OS
# for example, use 'yum' for the RedHat family of OSes, apt for Debian.
- name: setup
  setup:
  delegate_to: "{{ swvm['name'] }}"

- name: Install ASM packages
  ansible.builtin.package:
    name:
      - oracleasmlib
      - oracleasm-support
    state: installed
  delegate_to: "{{ swvm['name'] }}"
  become: true

- name: Run asmeverything.sh script
  script: "supporting_tools/asmeverything.sh"
  delegate_to: "{{ swvm['name'] }}"
  become: true


